name: climaprob-api
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - xarray
  - netcdf4
  - cftime
  - bottleneck
  - dask-core
  - scipy
  - pip:
      - fastapi==0.115.5
      - uvicorn[standard]==0.30.6
      - gunicorn==22.0.0
      - pydantic-settings==2.4.0
      - python-dotenv==1.0.1
      - requests==2.32.3
      - pydap==3.4.1
      - earthaccess==0.9.1
      - scikit-learn==1.5.2
      - statsmodels==0.14.2
      - redis==5.0.8
      - diskcache==5.6.3
      - loguru==0.7.2
      - pytest==8.3.3
      - pytest-cov==5.0.0
      - ruff==0.6.9
      - black==24.8.0
      - ipykernel==6.29.5
      - jupyterlab==4.2.5
